# Generated by Django 4.1.3 on 2022-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
